- type: docker-containers
  hide-by-default: false
  containers:
    nextcloud-aio-nextcloud:
      name: Nextcloud
      url: https://nextcloud.pylereyes.com/
      icon: si:nextcloud
      id: nextcloud
    nextcloud-aio-mastercontainer:
      name: Master Container
      parent: nextcloud
    nextcloud-aio-database:
      name: DB
      parent: nextcloud
    nextcloud-aio-fulltextsearch:
      name: Full Text Search
      parent: nextcloud
    nextcloud-aio-imaginary:
      name: Imaginary
      parent: nextcloud
    nextcloud-aio-notify-push:
      name: Notify Push
      parent: nextcloud
    nextcloud-aio-whiteboard:
      name: Whiteboard
      parent: nextcloud
    nextcloud-aio-apache:
      name: Apache
      parent: nextcloud
    nextcloud-aio-clamav:
      name: Clam AV
      parent: nextcloud
    nextcloud-aio-redis:
      name: Redis
      parent: nextcloud
    nextcloud-aio-talk:
      name: Talk
      parent: nextcloud
    nextcloud-aio-collabora:
      name: Collabora
      parent: nextcloud

    glance:
      name: Glance
      url: https://glance.pylereyes.com/
      icon: auto-invert sh:glance-dark
      id: glance

    openspeedtest:
      name: Speedtest
      url: http://10.9.11.2:3000
      icon: auto-invert sh:speedtest-dark
      id: speedtest

    jellyseerr:
      name: Jellyseerr
      url: https://jellyseerr.pylereyes.com/
      icon: auto-invert sh:jellyseerr-dark
      description: Media Request Management
      id: jellyseerr

    romm:
      name: Romm
      icon: auto-invert sh:romm-dark
      url: https://romm.pylereyes.com
      description: Rom Manager
      id: romm
    romm-db:
      name: DB
      parent: romm

    grocy:
      name: Grocy
      url: https://grocy.pylereyes.com
      icon: auto-invert sh:grocy-dark
      description: Home Inventory
      id: grocy

    komodo-core:
      name: Komodo
      url: https://komodo.pylereyes.com
      icon: auto-invert sh:komodo-dark
      description: Docker Container Manager
      id: komodo
    komodo-mongo-1:
      name: MongoDB
      parent: komodo
    komodo-periphery-1:
      name: Periphery
      parent: komodo

    ntfy:
      name: Ntfy
      icon: auto-invert sh:ntfy-dark
      description: Self Hosted Push Notification Server
      id: ntfy

    newt:
      name: Newt
      icon: auto-invert sh:pangolin-dark
      description: Agent for Pangolin
      id: newt

    qbittorrent:
      name: qBittorrent
      url: http://10.9.11.2:8489
      icon: auto-invert sh:qbittorrent-dark
      description: Media Acquisition
      id: arrstack
    prowlarr:
      name: Prowlarr
      parent: arrstack
    vpn:
      name: VPN
      parent: arrstack
    radarr:
      name: Radarr
      parent: arrstack
    sonarr:
      name: Sonarr
      parent: arrstack
    mylar:
      name: Mylar
      parent: arrstack
    bazarr:
      name: Bazarr
      parent: arrstack
    
    

    