- name: Home
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - type: server-stats
          servers:
            - type: local
              name: Services

        - type: releases
          cache: 14d
          # Without authentication the Github API allows for up to 60 requests per hour. You can create a
          # read-only token from your Github account settings and use it here to increase the limit.
          # token: ...
          repositories:
            - glanceapp/glance
            - goauthentik/authentik
            - nextcloud/server

        - type: custom-api
          title: Steam Specials
          cache: 12h
          url: https://store.steampowered.com/api/featuredcategories?cc=us
          template: |
            <ul class="list list-gap-10 collapsible-container" data-collapse-after="5">
            {{ range .JSON.Array "specials.items" }}
              <li>
                <a class="size-h4 color-highlight block text-truncate" href="https://store.steampowered.com/app/{{ .Int "id" }}/">{{ .String "name" }}</a>
                <ul class="list-horizontal-text">
                  <li>{{ div (.Int "final_price" | toFloat) 100 | printf "$%.2f" }}</li>
                  {{ $discount := .Int "discount_percent" }}
                  <li{{ if ge $discount 40 }} class="color-positive"{{ end }}>{{ $discount }}% off</li>
                </ul>
              </li>
            {{ end }}
            </ul>

    - size: full
      widgets:
        - type: search
          search-engine: kagi
          autofocus: true
          bangs:
            - title: YouTube
              shortcut: "!yt"
              url: https://www.youtube.com/results?search_query={QUERY}
        - type: videos
          channels:
            - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
            - UCoal_hpPIPAnWlG-kWHLheA # Drawfee
            - UCpKaZzU4K8X6i-9TXkiRikA # Drawfee Extra
            - UChIs72whgZI9w6d6FhwGGHA # Gamers Nexus
            - UCI8iQa1hv7oV_Z8D35vVuSg # Hardware Unboxed
        - $include: dockercontainers.yml
        - type: rss
          limit: 25
          collapse-after: 8
          cache: 15m
          feeds:
            - url: https://www.engadget.com/rss.xml
              title: Engadget
            - url: https://www.theverge.com/rss/index.xml
              title: The Verge
            - url: https://9to5mac.com/feed/
              title: 9to5Mac

    - size: small
      widgets:
        - type: weather
          location: Tooele, Utah, United States
          units: imperial # alternatively "imperial"
          hour-format: 24h # alternatively "24h"
          # Optionally hide the location from being displayed in the widget
          hide-location: true
        # - type: calendar
        #   first-day-of-week: monday
        - $include: nextdns.yml
        - $include: tailscaledevices.yml