---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-admin
  namespace: couchdb
spec:
  encryptedData:
    COUCHDB_PASSWORD: AgAO+89LkEf7LMxTna3jd05OuslEPTSEP2NwYTNEF1s1kNc0lqUbZ2nQ9PNgQ+ELshpMYZy37vr1JgxRvK4QBNKVVpGDxb+XDEsiZZ2n3s6Vg4mZzPz9ZqCsGfH7i66Jssnnf6WnGU/s1SfqAkiBTdIWNQb4pKdOXNcyPd+8B6DNWOdg146JVR707vB8gm65Icpq+yeBKEB96S7njUX5qNL0tIKyxIMBzgsA3S8ibLLGXDou+hDyC698G73Hb89q6UxkGXLcWTe7UTAPIG5UHYyAUt4zYvks2A4U+PAQL5JeU3/OY5mwQLNpY0ISD3Pf3Sn8S0zBeFZFB4BPuIcG8kN/HaAbSFaOVBcKMUuBU/jZkmesHHcuJLfCi0oEOusDOJUGYUd7LQ7ksfmQemWsX9Jg2EUyc8lpsTNLO3rbqt4OLFlrBZKDavC7+fsaBNYY0DaJqvxdlWS+kAZckfslWzMLSFd44CtUK+FXSKvh+qptRBlE4jH9KtbkGVvNlFu+LkBiH4OcntzIUT5fwjAL5CLaPSna78gjYMuWw6tkX5dBvMKphKFRt7R6q95zIBI52+Tc4LNVnpgRhAKMz9KMSV9sUEBKKRkC9ipcycQ1MEIYJI/NuvSdCfNHDUGWpJPe37fzUhOlWzFTGkkynsy0KcfUQc6E9agfiwD9IL5Cp6Dz1htUMpzQhf2qrBWliD8x6jX3Zpn7rmGXlpEGWyX1aL0oOgFKNpAYv9RJ4GwfHs6P2A==
    COUCHDB_USER: AgBg36REINFZneqxYIhEA3GUnsB7Nzfuk0shMCgeP8oqgPlLoD362YphrT8mEtglrPw/u0y8MIEU5KKL7/cfU7cLNBpHWOgwlrhX7DALFv5G9ekEPJJonTvnSyhJPxRekc7PUzdMp/Zu3ZIOUL9pK3t3tcPqBbd+mXHGw/p11LKDDHzG1kt05xnX7N7h+bV3HqcdU9lROrXcft1DiTUPv3D/slCGQWPQrsShLUBXWtlFIvMYo8mqSxSWtd0vJ8SqlqamX0bfvcHUv6I+0cTnI1kWt5LJPHDx67B3x4KFq3qTvnCXtl86q70GtNjTrG7Nt/TMWB7PuxdMyMz+/5ZM6PymVniIkypYimJgzOXKi5w2Q/KKltwAlgn4j+qJIz7MVgqyBcuOvG7/3ZnmTu96r2fuHBVPqkNkHz0gA5BjRltqZlWDrNflLgyLsS+UX2XBXaJXahDNXHHOAAO3kPMQw1FOus2EErtx4Fu78FXvzWZ9aEnNE0fBYtZtCNhw4hTgktt0GGBEc+BJeYArmJ4xj2mKgbn9Szl25BeIEXu09wMqhNRbMR7yUfBCeai3axs4J863ewyWMtpdbt+Ug4ETsmSPITErYgYu1Hlj2ZXKk4CDW4oLhnrsBxajqa76SZ8LCeYh1qKo1YPNJsXSvuIg9bZFrzsVEEhQnw84BjneQQEcJ2NK5VpYshpzySHXt6BVSui3z7aQRw==
  template:
    metadata:
      name: couchdb-admin
      namespace: couchdb
