apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchdb
  namespace: couchdb
spec:
  serviceName: couchdb-headless
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
        - name: couchdb
          image: couchdb:3.5.2.1
          ports:
            - containerPort: 5984
          env:
            - name: COUCHDB_USER
              valueFrom:
                secretKeyRef:
                  name: couchdb-admin
                  key: COUCHDB_USER
            - name: COUCHDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: couchdb-admin
                  key: COUCHDB_PASSWORD
          volumeMounts:
            - name: couchdb-data
              mountPath: /opt/couchdb/data
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 1Gi
  volumeClaimTemplates:
    - metadata:
        name: couchdb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
