apiVersion: v1
data:
  WIREGUARD_PRIVATE_KEY: TUxaSVFRL0RodGFEK3I3c2ErZktjakdKWDZmSmlvSGNjMzlJb3lVUWtXcz0=
kind: Secret
metadata:
  creationTimestamp: null
  name: gluetun-secrets
  namespace: arr-stack
