---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-secrets
  namespace: arr-stack
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgAbb66eEk7VB9IPSCwT6aJwu09lWip59W+QwfQrARrrKLUkI4km6lzropebllAtrxBj2JoF2XNcW9mF+owwHbSmkNmbz4oXH7IxTpAQfkNROC/6cdiAG5wfl6oG4cUoGSmOkydddYKEdGAzXaxnnhG90FtH0Akv0iT1lQMn7qXxVK0upa0QFAp3GGw/VvA18UOvIqnP54boZPa3PYTw93NCbkk3+dr//4IENG9udqfnjMGp7kPYeUoss99Fq+YwJOlPFkHWm0P450nUvr7g1Q0X1FuFOXqo9QxReOIwyD8sdslphzbifkMu/+WO9ST6TtfI4/xRU8UcVsQp1Oolmkqsx2uEGcIdHffsxk2EsgIoL8Y33IdnnQveLVKfVwPa9+mVpheIbhu8O/aQfU/WiU1XcEwvzS40E5ARlHxlgM0rzW2dZ9sTrlGqkh1vCeD4Egi4+ZwTV2yaNlslU//fyjy0EOm9ft1c8UMTAdnqju4rzsFpt4B1Ix6bYUbf7FFUxRpVBy03MBO2/1164olBOIwHqo0Z52/Fk1/Y7qeNiQY8xRADVP35pPn+rVYv+tRf4BOscqQmWrfVTzxoOuc3yepc85Dd5nZKFATpPoLggZbc4iUqSxmPO13MvXquTDTVkYJqgxaHLLX0zDk1KUWOJk7odEg/iRXevUxYkMH0FMXjOlZcb3nNk20cCWA9PClMURka88HW7tjFns8zXobndmkoNyq4YZ4NfOoUGKXrum/5i4YPKlXW3SF92XkdLw==
  template:
    metadata:
      name: gluetun-secrets
      namespace: arr-stack
