services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    networks:
      pangolin-frontend:
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      # Optionally, also mount docker socket if you want to use the docker containers widget
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8085:8080
    env_file: .env

networks:
  pangolin-frontend:
    external: true
